# Generated by Django 4.2.27 on 2025-12-27 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0002_trainingtimeslot'),
        ('leads', '0003_lead_instructor_tariff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='training_time',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dictionaries.trainingtimeslot'),
        ),
    ]
