# Generated by Django 4.2.27 on 2025-12-27 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingTimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name_ru', models.CharField(max_length=255)),
                ('name_kz', models.CharField(max_length=255)),
                ('emoji', models.CharField(blank=True, max_length=10, null=True)),
                ('time_range_ru', models.CharField(blank=True, max_length=50, null=True)),
                ('time_range_kz', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'dict_training_time_slot',
                'ordering': ['sort_order', 'id'],
                'indexes': [models.Index(fields=['is_active', 'sort_order'], name='dict_traini_is_acti_a2542c_idx')],
            },
        ),
    ]
