# Generated by Django 4.2.27 on 2025-12-29 18:30

from django.db import migrations


def create_online_tariff_plans(apps, schema_editor):
    """Создать тарифные планы для онлайн-продуктов"""
    TariffPlan = apps.get_model('dictionaries', 'TariffPlan')
    
    # Создаем только если их еще нет
    plans = [
        {
            'code': 'PDD_TESTS',
            'name_ru': 'ПДД-тесты (только тесты)',
            'name_kz': 'ЖҚЕ тесттері (тек тесттер)',
            'sort_order': 20,
            'is_active': True,
        },
        {
            'code': 'ONLINE_START',
            'name_ru': 'Онлайн START (теория + тесты)',
            'name_kz': 'Онлайн START (теория + тесттер)',
            'sort_order': 21,
            'is_active': True,
        },
        {
            'code': 'ONLINE_PRO_DRIVE',
            'name_ru': 'Онлайн PRO + Вождение (1 занятие)',
            'name_kz': 'Онлайн PRO + Жүргізу (1 сабақ)',
            'sort_order': 22,
            'is_active': True,
        },
    ]
    
    for plan_data in plans:
        TariffPlan.objects.get_or_create(
            code=plan_data['code'],
            defaults=plan_data
        )


def reverse_create_online_tariff_plans(apps, schema_editor):
    """Удалить тарифные планы для онлайн-продуктов"""
    TariffPlan = apps.get_model('dictionaries', 'TariffPlan')
    TariffPlan.objects.filter(code__in=['PDD_TESTS', 'ONLINE_START', 'ONLINE_PRO_DRIVE']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0002_trainingtimeslot'),
    ]

    operations = [
        migrations.RunPython(create_online_tariff_plans, reverse_create_online_tariff_plans),
    ]
