# Generated by Django 4.2.27 on 2025-12-22 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0001_initial'),
        ('catalog', '0002_remove_instructor_price_kzt_instructor_categories_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='schooltariff',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='schooltariff',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dictionaries.category'),
        ),
        migrations.AddField(
            model_name='schooltariff',
            name='training_format',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dictionaries.trainingformat'),
        ),
        migrations.AlterUniqueTogether(
            name='schooltariff',
            unique_together={('school', 'tariff_plan', 'category', 'training_format')},
        ),
        migrations.AddIndex(
            model_name='schooltariff',
            index=models.Index(fields=['category', 'training_format', 'is_active'], name='school_tari_categor_b6bec0_idx'),
        ),
    ]
