# Generated by Django 4.2.27 on 2025-12-27 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0002_trainingtimeslot'),
        ('catalog', '0003_add_category_and_training_format_to_school_tariff'),
    ]

    operations = [
        migrations.AddField(
            model_name='schooltariff',
            name='training_times',
            field=models.ManyToManyField(blank=True, related_name='tariffs', to='dictionaries.trainingtimeslot'),
        ),
    ]
