# Generated by Django 4.2.27 on 2025-12-27 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0002_trainingtimeslot'),
        ('catalog', '0004_schooltariff_training_times'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='schooltariff',
            name='school_tari_categor_b6bec0_idx',
        ),
        migrations.AlterUniqueTogether(
            name='schooltariff',
            unique_together={('school', 'tariff_plan', 'training_format')},
        ),
        migrations.AddField(
            model_name='schooltariff',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='tariffs', to='dictionaries.category'),
        ),
        migrations.AddIndex(
            model_name='schooltariff',
            index=models.Index(fields=['training_format', 'is_active'], name='school_tari_trainin_a99766_idx'),
        ),
        migrations.RemoveField(
            model_name='schooltariff',
            name='category',
        ),
    ]
