# Generated by Django 4.2.27 on 2025-12-29 18:30

from django.db import migrations


def create_online_school_tariffs(apps, schema_editor):
    """Создать школу АвтоТехАрна и тарифы для онлайн-продуктов"""
    School = apps.get_model('catalog', 'School')
    SchoolTariff = apps.get_model('catalog', 'SchoolTariff')
    City = apps.get_model('dictionaries', 'City')
    Category = apps.get_model('dictionaries', 'Category')
    TariffPlan = apps.get_model('dictionaries', 'TariffPlan')
    TrainingFormat = apps.get_model('dictionaries', 'TrainingFormat')
    TrainingTimeSlot = apps.get_model('dictionaries', 'TrainingTimeSlot')
    
    # Найти или создать школу "АвтоТехАрна"
    # Используем первый доступный город (обычно Атырау с id=1)
    city = City.objects.filter(is_active=True).first()
    if not city:
        # Если нет городов, пропускаем создание
        return
    
    # Проверяем, существует ли уже школа "АвтоТехАрна"
    school = School.objects.filter(name_ru='АвтоТехАрна').first()
    if not school:
        # Создаем школу только если её нет
        school = School.objects.create(
            city=city,
            name_ru='АвтоТехАрна',
            name_kz='АвтоТехАрна',
            rating=0,
            trust_index=0,
            address_ru='Онлайн',
            address_kz='Онлайн',
            is_active=True,
        )
    
    # Получаем необходимые объекты
    online_format = TrainingFormat.objects.filter(name_ru='Онлайн').first()
    if not online_format:
        # Если формат "Онлайн" не найден, используем первый доступный
        online_format = TrainingFormat.objects.filter(is_active=True).first()
    
    # Получаем все категории для PDD_TESTS
    all_categories = list(Category.objects.filter(is_active=True))
    
    # Получаем категорию B для START и PRO
    category_b = Category.objects.filter(code='B', is_active=True).first()
    
    # Получаем все времена обучения (MORNING, DAY, EVENING)
    all_times = list(TrainingTimeSlot.objects.filter(is_active=True))
    
    # Получаем тарифные планы
    pdd_plan = TariffPlan.objects.filter(code='PDD_TESTS').first()
    start_plan = TariffPlan.objects.filter(code='ONLINE_START').first()
    pro_plan = TariffPlan.objects.filter(code='ONLINE_PRO_DRIVE').first()
    
    if not all([pdd_plan, start_plan, pro_plan, online_format]):
        # Если не все необходимые объекты найдены, пропускаем
        return
    
    # 1. ПДД-тесты (8 000 ₸)
    if pdd_plan:
        pdd_tariff, _ = SchoolTariff.objects.get_or_create(
            school=school,
            tariff_plan=pdd_plan,
            training_format=online_format,
            defaults={
                'price_kzt': 8000,
                'currency': 'KZT',
                'description_ru': (
                    'Только ПДД-тесты (АвтоЦОН).\n'
                    '• Выбор категории\n'
                    '• Подготовка к теоретическому экзамену\n'
                    '• Без видеоуроков\n'
                    '• Без сертификата'
                ),
                'description_kz': (
                    'Тек ЖҚЕ тесттері (АвтоЦОН).\n'
                    '• Санатты таңдау\n'
                    '• Теориялық емтиханға дайындық\n'
                    '• Видео сабақтар жоқ\n'
                    '• Сертификат жоқ'
                ),
                'is_active': True,
            }
        )
        # Добавляем все категории и времена
        pdd_tariff.categories.set(all_categories)
        pdd_tariff.training_times.set(all_times)
    
    # 2. Онлайн START (15 000 ₸)
    if start_plan and category_b:
        start_tariff, _ = SchoolTariff.objects.get_or_create(
            school=school,
            tariff_plan=start_plan,
            training_format=online_format,
            defaults={
                'price_kzt': 15000,
                'currency': 'KZT',
                'description_ru': (
                    'Онлайн START:\n'
                    '• Видеоразборы от Миры\n'
                    '• Доступ к ПДД-тестам\n'
                    '• Чат-поддержка\n'
                    'Категория: B'
                ),
                'description_kz': (
                    'Онлайн START:\n'
                    '• Мирадан видео талдаулар\n'
                    '• ЖҚЕ тесттеріне қолжетімділік\n'
                    '• Чат-қолдау\n'
                    'Санат: B'
                ),
                'is_active': True,
            }
        )
        # Добавляем только категорию B и все времена
        start_tariff.categories.set([category_b])
        start_tariff.training_times.set(all_times)
    
    # 3. Онлайн PRO + Вождение (60 000 ₸)
    if pro_plan and category_b:
        pro_tariff, _ = SchoolTariff.objects.get_or_create(
            school=school,
            tariff_plan=pro_plan,
            training_format=online_format,
            defaults={
                'price_kzt': 60000,
                'currency': 'KZT',
                'description_ru': (
                    'Онлайн PRO + Вождение:\n'
                    '• Всё из START\n'
                    '• 1 индивидуальное занятие по вождению\n'
                    '• Персональные рекомендации\n'
                    '• Сертификат\n'
                    'Категория: B'
                ),
                'description_kz': (
                    'Онлайн PRO + Жүргізу:\n'
                    '• START-тан барлығы\n'
                    '• Жүргізу бойынша 1 жеке сабақ\n'
                    '• Жеке ұсыныстар\n'
                    '• Сертификат\n'
                    'Санат: B'
                ),
                'is_active': True,
            }
        )
        # Добавляем только категорию B и все времена
        pro_tariff.categories.set([category_b])
        pro_tariff.training_times.set(all_times)


def reverse_create_online_school_tariffs(apps, schema_editor):
    """Удалить тарифы и школу для онлайн-продуктов"""
    School = apps.get_model('catalog', 'School')
    SchoolTariff = apps.get_model('catalog', 'SchoolTariff')
    TariffPlan = apps.get_model('dictionaries', 'TariffPlan')
    
    pdd_plan = TariffPlan.objects.filter(code='PDD_TESTS').first()
    start_plan = TariffPlan.objects.filter(code='ONLINE_START').first()
    pro_plan = TariffPlan.objects.filter(code='ONLINE_PRO_DRIVE').first()
    
    plans = [p for p in [pdd_plan, start_plan, pro_plan] if p]
    if plans:
        SchoolTariff.objects.filter(tariff_plan__in=plans).delete()
    
    # Удаляем школу только если у неё больше нет тарифов
    school = School.objects.filter(name_ru='АвтоТехАрна').first()
    if school and not school.tariffs.exists():
        school.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_remove_schooltariff_school_tari_categor_b6bec0_idx_and_more'),
        ('dictionaries', '0003_add_online_tariff_plans'),
    ]

    operations = [
        migrations.RunPython(create_online_school_tariffs, reverse_create_online_school_tariffs),
    ]
