# Generated by Django 4.2.27 on 2025-12-29 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_add_online_school_tariffs'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='school',
            constraint=models.UniqueConstraint(fields=('name_ru',), name='unique_school_name_ru'),
        ),
    ]
